services:
  ddns-bot:
    build: .
    container_name: ddns-bot
    restart: unless-stopped
    network_mode: "host"
    environment:
      # Discord Bot
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - AUTO_UPDATE_INTERVAL=${AUTO_UPDATE_INTERVAL}
      
      # Cloudflare
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      
      # MySQL (auf localhost vom Host)
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSORD_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      
      # Web Interface
      - WEB_USERNAME=${WEB_USERNAME}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - WEB_PORT=5000
      - WEB_HOST=0.0.0.0
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      
      # Certbot
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./templates:/app/templates
    extra_hosts:
      - "host.docker.internal:host-gateway"
